feat: дать пользователям возможность бронировать вещи
Nikitacauselove/java-shareit pull request #2
Opened 2023-07-18 23:56 UTC by Nikitacauselove

2023-07-19 07:18 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть парочка совсем мелких замечаний!

Желаю удачи!

2023-07-19 07:18 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        throw new ConflictException("Пользователь с указанным адресом электронной почты уже существует.");
По возможности стоит использовать конструкцию `.ifPresentOrElse`

2023-07-19 07:18 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        } else {
`else` здесь не нужен, выполнение этого метода после условного оператора и так будет только в том случае, если мы в него не заходили, так как там мы всегда делаем `return`.

Таким образом мы можем сократить вложенность кода

2023-07-19 17:42 UTC, Nikitacauselove commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        throw new ConflictException("Пользователь с указанным адресом электронной почты уже существует.");
Спасибо, буду иметь в виду. Я попробовал использовать `.ifPresentOrElse`, но код получился менее читаемым. Если вы напишете, как эту конструкцию здесь можно применить, то буду благодарен

2023-07-20 09:29 UTC, LexLippi approved these changes
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2023-07-20 09:29 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        throw new ConflictException("Пользователь с указанным адресом электронной почты уже существует.");
```java
return userRepository.findByEmail(user.getEmail())
    .map(userWithSameEmail -> {
        if (!userWithSameEmail.hasSameId(user)) {
            throw new ConflictException("Пользователь с указанным адресом электронной почты уже существует.");
        }
        return userRepository.save(user);
    })
    .orElseGet(() -> userRepository.save(user));
```

2023-07-20 15:25 UTC, merged